### ISSUE TITLE
module "QuickPromise" is not installed

### ISSUE THREAD

**Issue by Steamrunner** [0x20/tab-ui#9]
Running /usr/bin/tab-ui returns following error:

QQmlApplicationEngine failed to load component
qrc:/main.qml:5:1: module "QuickPromise" is not installed

using ubuntu 20.10

**Comment by thequux** [comment]
Run `git submodule update --init` and rebuild; that should fix it.

**Comment by thequux** [comment]
I added a README with building instructions, so this shouldn't come up again.
